services:
  3proxy:
    image: 3proxy/3proxy:latest
    container_name: 3proxy
    restart: unless-stopped
    volumes:
      - ./3proxy/3proxy.cfg:/etc/3proxy/3proxy.cfg:ro
    networks:
      - proxy-net
    expose:
      - "8080"
      - "1080"

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: unless-stopped
    ports:
      - "5445:5445"
      - "8404:8404"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "fd00:0:0:1::/64"
